function makingdifferentcodegen(){
var mdnitFurl=document.getElementsByName("mdfurl")[0].value;
var mdFurl=mdnitFurl.replace(/\s/gi,"");
var mdEFurl=encodeURIComponent(mdFurl);
var widget=document.getElementsByName("widget.content")[0];
widget.value = "<style type='text\/css'>\n";
widget.value += "#makingdifferentpopup{\n";
widget.value += "position:absolute;\n";
widget.value += "top:100px;\n";
widget.value += "z-index:999;\n";
widget.value += "display:none;\n";
widget.value += "padding:0px;\n";
widget.value += "right:600px;\n";
widget.value += "border:10px solid #6F6F6F;\n";
widget.value += "-webkit-border-radius:8px 8px 8px 8px;\n";
widget.value += "-moz-border-radius:8px 8px 8px 8px;\n";
widget.value += "border-radius:8px 8px 8px 8px;\n";
widget.value += "width:400px;\n";
widget.value += "height:360px;\n";
widget.value += "overflow:hidden;\n";
widget.value += "}\n";
widget.value += "#makingdifferentpopup h1{\n";
widget.value += "background:#6d84b4 url(http:\/\/4.bp.blogspot.com\/-rNUTIpDQ21s\/T0NqE_vv6GI\/AAAAAAAACps\/GSoWE2n9Oy8\/s1600\/%255Bwww.gj37765.blogspot.com%255Dh1.png) 98% no-repeat;\n";
widget.value += "border:1px solid #3b5998 !important;\n";
widget.value += "color:#FFFFFF !important;\n";
widget.value += "font-size:20px !important;\n";
widget.value += "font-weight:700 !important;\n";
widget.value += "padding:5px !important;\n";
widget.value += "margin:0 !important;\n";
widget.value += "font-family:'\"lucida grande\",tahoma,verdana,arial,sans-serif !important;";
widget.value += "overflow:hidden !important;\n";
widget.value += "}\n";
widget.value += ".htmlarea{\n";
widget.value += "font-size:12px !important;\n";
widget.value += "font-weight:normal !important;\n";
widget.value += "height:265px !important;\n";
widget.value += "padding:1px !important;\n";
widget.value += "background:#fff !important;\n";
widget.value += "border-bottom:2px solid #ddd;\n";
widget.value += "overflow:hidden !important;\n";
widget.value += "}\n";
widget.value += "#mdfooter{\n";
widget.value += "background:#F2F2F2 !important;\n";
widget.value += "height:56px !important;\n";
widget.value += "padding:10px 10px 10px 10px !important;\n";
widget.value += "overflow:hidden !important;\n";
widget.value += "}\n";
widget.value += "#mdclose{\n";
widget.value += "float:right;\n";
widget.value += "background-color:#eee !important;\n";
widget.value += "border:1px solid #ccc !important;\n";
widget.value += "color:#111 !important;\n";
widget.value += "font-weight:bold !important;\n";
widget.value += "padding:5px 8px 5px 8px !important;\n";
widget.value += "text-decoration:none !important;\n";
widget.value += "display:inline-block !important;\n";
widget.value += "font-family:'\"lucida grande\",tahoma,verdana,arial,sans-serif !important;\n";
widget.value += "outline:none !important;\n";
widget.value += "position:relative !important;\n";
widget.value += "font-size:18px !important;\n";
widget.value += "margin:1px !important;\n";
widget.value += "}\n";
widget.value += "#mdclose:active{\n";
widget.value += "top:1px;\n";
widget.value += "left:1px;\n";
widget.value += "}\n";
widget.value += ".htmlarea span{\n";
widget.value += "bottom:80px;\n";
widget.value += "font:8px \"lucida grande\",tahoma,verdana,arial,sans-serif;\n";
widget.value += "position:absolute;\n";
widget.value += "right:6px;\n";
widget.value += "text-align:right;\n";
widget.value += "z-index: 99999;\n";
widget.value += "}\n";
widget.value += ".htmlarea span a{\n";
widget.value += "color: #000;\n";
widget.value += "text-decoration:none;\n";
widget.value += "}\n";
widget.value += ".htmlarea span a:hover{\n";
widget.value += "text-decoration:underline;\n";
widget.value += "}\n";
widget.value += "<\/style>\n";
widget.value += "<script type='text\/javascript'>\n";
widget.value += "jQuery(document).ready(function() {\n";
widget.value += "function makingdifferent_ppopup()  {\n";
widget.value += "var mdwh = jQuery(window).height();\n";
widget.value += "var mdpph = jQuery(\"#makingdifferentpopup\").height();\n";
widget.value += "var mdfromTop = jQuery(window).scrollTop()+50;\n";
widget.value += " jQuery(\"#makingdifferentpopup\").css({\"top\":mdfromTop});\n";
widget.value += "}jQuery(window)\n";
widget.value += ".scroll(makingdifferent_ppopup)\n";
widget.value += ".resize(makingdifferent_ppopup)\n";
widget.value += "\/\/alert(jQuery.cookie('sreqshown'));\n";
widget.value += "\/\/var mdww = jQuery(window).width();\n";
widget.value += "\/\/var mdppw = jQuery(\"#makingdifferentpopup\").width();\n";
widget.value += "\/\/var mdleftm = (mdww-mdppw)\/2;\n";
widget.value += "var mdleftm = 500;\n";
widget.value += "\/\/var mdwh = jQuery(window).height();\n";
widget.value += "\/\/var mdpph = jQuery(\"#makingdifferentpopup\").height();\n";
widget.value += "\/\/var mdfromTop = (jQuery(window).scrollTop()+mdwh-mdpph) \/ 2; \n";
widget.value += "jQuery(\"#makingdifferentpopup\").animate({opacity: \"1\", left: \"0\" , left:\n mdleftm}, 0).show();\n     ";
widget.value += "jQuery(\"#mdclose\").click(function() {\n";
widget.value += "jQuery(\"#makingdifferentpopup\").animate({opacity: \"0\", left: \"-5000000\"}, 1000).show(); });});\n";
widget.value += "<\/script>\n";
widget.value += "\n";
widget.value += "<div id=\"makingdifferentpopup\">\n";
widget.value += "<h1>Join us on facebook<\/h1>\n";
widget.value += "<div class=\"htmlarea\">\n";
widget.value += "<iframe src=\"\/\/www.facebook.com\/plugins\/likebox.php?href="+mdEFurl+"&amp;width=400&amp;colorscheme=light&amp;show_faces=true&amp;border_color=%23fff&amp;stream=false&amp;header=false&amp;height=250\" scrolling=\"no\" frameborder=\"0\" style=\"border:none; overflow:hidden; width:400px; height:250px;\" allowtransparency=\"true\">\n<\/iframe>\n";
widget.value += "<span>\n";
widget.value += "By <a href=\"http:\/\/www.gj37765.blogspot.com\/\" target=\"_blank\">Making DIfferent<\/a> \/ <a href=\"http:\/\/gj37765.blogspot.in\/2012\/05\/add-facebook-type-pop-up-for-facebook.html\" target=\"_blank\">+Get This!<\/a>\n";
widget.value += "<\/span>\n";
widget.value += "<\/div>\n";
widget.value += "<div id=\"mdfooter\">\n";
widget.value += "<a href=\"#\" id=\"mdclose\" onclick=\"return false;\">Cancel<\/a>\n";
widget.value += "<\/div>\n";
document.getElementsByName("go")[0].disabled=false}
